// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvACMz_XuWAXJJP8g3ZmuhV9AVa72sMek',
    appId: '1:415620324113:web:929c9ea306372280808ab0',
    messagingSenderId: '415620324113',
    projectId: 'airplane-bwa-2202',
    authDomain: 'airplane-bwa-2202.firebaseapp.com',
    storageBucket: 'airplane-bwa-2202.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk3KpIocEdWOcMDb8y6h8_xl-ZFtlsHEo',
    appId: '1:415620324113:android:b34ac268d51c3877808ab0',
    messagingSenderId: '415620324113',
    projectId: 'airplane-bwa-2202',
    storageBucket: 'airplane-bwa-2202.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBL7EEiH5tiX9o24Bje_YS0aGyAx16bZvU',
    appId: '1:415620324113:ios:b4dab8fe3fea704f808ab0',
    messagingSenderId: '415620324113',
    projectId: 'airplane-bwa-2202',
    storageBucket: 'airplane-bwa-2202.appspot.com',
    iosBundleId: 'com.example.bwaMasteringflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBL7EEiH5tiX9o24Bje_YS0aGyAx16bZvU',
    appId: '1:415620324113:ios:a0f8ee6b8011e481808ab0',
    messagingSenderId: '415620324113',
    projectId: 'airplane-bwa-2202',
    storageBucket: 'airplane-bwa-2202.appspot.com',
    iosBundleId: 'com.example.bwaMasteringflutter.RunnerTests',
  );
}
